spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: dyp
      username: cassandra
      password: cassandra
      schema-action: none
      local-datacenter: datacenter1